# Exception Safety

**Livello base:**

1. Il codice non "ruba" risorse.
2. Codice neutrale rispetto alle eccezioni
3. Gli oggetti sui quali sui quali si stava lavorando soddisvano le loro invarianti (sono distruggibili senza causare *undefined behavoir*)

Se sto facendo operazioni su una struttura dati e durante queste operazioni qualcosa va male, al momento dell'errore, la struttura dati, in che stato è?

Un modo è trattare le operazioni delle strutture dati come delle transizioni implementando le proprietà **ACID**, permettendo alla struttura dati di tornare a uno stato funzionante se qualche operazione va male.

**Livello forte:**

1. Semantica atomica: o tutto o niente.

**Livello no-throw:**

1. Assumo che le mie operazioni non lancino mai un'eccezione. Non posso applicare questo livello a tutte le operazioni della mia struttura dati. Di solito applico questo livello alle funzioni che gestiscono le eccezioni e liberano le risorse (in quanto non *devono* uscire delle eccezioni da tali funzioni), assegnamento a tipi built-in, funzioni di swap su tupi built-in e in tutte quelle funzioni che per documentazioni assicurano l'assenza di eccezioni.

I distruttori **non devono mai** far uscire delle eccezioni. 

Nel caso del RAII, se ho un'eccezione in una funzione, quando finisce lo scope di quella funzione il distruttore verrà richiamato, a quel punto se anche il distruttore solleverà un'eccezione il programma dovrà propagare due eccezioni, essendo una cosa impossibile da fare il programma va in *undefined behavoir*.

Progettare tre tipi di pila dinamica utilizzando C++98. Una non templatica con un tipi fissato utilizzando quante meno operazioni di modo di usare questa classe in quella templatica, tecnica comune di fare "clone" di una classe. La terza versione assomiglierà più ai contenitori STL.

Programmare e utilizzare oggetti templatici è scomodo perchè il compilatore ha la tendenza di dare degli errori che sono meno precisi rispetto a quando utilizziamo degli oggetti non templatici.

``` c++
#include "Stack.hh"

#include <iostream>
#include <string>

typedef std::string T;

void prova(){
  Stack s1;
  assert(s1.size() == 0);
  assert(s1.isempty());

  std::cerr << "\n\n ### fine fase 1 ### \n\n";

  Stack s2(s1);
  assert(s1.size() == 0 && s2.size() == 0);

  std::cerr << "\n\n ### fine fase 2 ### \n\n";

  s2.push("aaa");
  
  /* Visto che s2 è una copia di s1, con la assert sotto mi assicuro che  il valore sia stato copiato e non passato per riferimento
  */
  
  assert(s1.size() == 0 && s2.size() == 1);

  std::cerr << "\n\n ### fine fase 3 ### \n\n";

  T& t = s2.top();
  assert(t == "aaa");
  t = "bbb";
  assert(s2.top() == "bbb");

  std::cerr << "\n\n ### fine fase 4 ### \n\n";

  Stack s3 = s2;
  assert(s2.size() == 1 && s3.size() == 1 && s3.top() == s2.top());

  std::cerr << "\n\n ### fine fase 5 ### \n\n";

  s3 = s2 = s1;     //Assegnamento concatenabile
  assert(s1.empty() && s2.empty() && s3.empty());

  std::cerr << "\n\n ### fine fase 6 ### \n\n";

}
```

Lo stack ha due concetti: il numero di elementi che sono memorizzabili e il numero di elementi che è possible memorizzare. L'invariente è che la capacità deve essere maggiore del numero di elementi effettivamente memorizzati nella pila.

Mi serve un tipo intero per memorizzare la size e la capacity dello staco, utilizzo ``typedef std::size_t size_type``

Il costruttore di default va dichiarato così:

``` c++
explicit Stack(size_type t = 16);

/*
metto explicit perchè voglio evitare conversioni implicite
*/
```

``` c++98
bool Stack::OK() const; //invariante di classe
```

Le inline:

``` c++
inline
Stack::Stack(const size_type capacity)
   : vec_(new value_type[capacity == 0 ? 16 : capacity}),
     capacity_(capacity == 0 ? 16 : capacity),
	 size_(0) {
	 //la capacità deve essere maggiore di 0.
	 assert(OK());
}

/*

È exception safe? 
La new è un tipo built-in ma può comunque dare eccezioni visto che alloca un blocco di memoria, l'eccezione è che non c'è più memoria dispnibile quindi mi da la bad_alloc. 
Ma anche se succede a noi non cambia niente visto che non è ancora stato fatto niente quindi non c'è niente da modificare, lasciamo propagare l'eccezione fino alla fine dello scope. 
Se ci sono problemi dopo la new, quando viene richiamata dopo l'errore la new garantisce exception safe, infatti si accorge dell'errore e disfa tutto. Il costruttore è quindi exception safe.

*/

inline
Stack::Stack(const Stack& y)
   : vec_(make_copy(y.vec_, y.size_, (y.size_ == 0) ? 1 : y-size_)),
     capacity_((y.size_ == 0) ? 1 : y.size_)
	 size_(y.size_) {
	 assert(OK());
}

inline
Stack::~Stack(){
   delete[] vec_;
   
   /* Avendo fatto la new con le parentesi quadre, anche la delete deve essere richiamata con le parentesi quadre
   */
}

/*
Il distruttore inizia a deallocare gli oggetti dall'ultimo, non farà eccezioni perchè il costruttore non ha generato eccezioni quindi è exception safe.
*/

inline void
Stack::swap(Stack& y){
   std::swap(vec_, y.vec_);
   std::swap(size_, y.size_);
   std::swap(capacity_, y.capacity_);
}

/*
La swap è una funzione di servizio, scambio anche tipi built-in quindi non genererà mai eccezioni e sarà molto efficiente.
Exception safe no throw
*/

inline Stack&
Stack::operator=(const Stack& y) {
   // Costruisco una copia di y e la scambio con this.
   Stack temp(y);
   swap(temp);
   return *this;
}

/*
Ho un exception safe forte, ma c'è la possibilità di avere eccezioni
*/
```
